INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('100000', 'Red Fedora', 'Official Red Hat Fedora', 34.99);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('329299', 'Quarkus T-shirt', 'This updated unisex essential fits like a well-loved favorite, featuring a crew neck, short sleeves and designed with superior combed and ring- spun cotton.', 10.00);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('329199', 'Pronounced Kubernetes', 'Kubernetes is changing how enterprises work in the cloud. But one of the biggest questions people have is: How do you pronounce it?', 9.00);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('165613', 'Knit socks', 'Your brand will get noticed on these full color knit socks. Imported.',4.15);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('165614', 'Quarkus H2Go water bottle', 'Sporty 16. 9 oz double wall stainless steel thermal bottle with copper vacuum insulation, and threaded insulated lid. Imprinted. Imported.', 14.45);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('165954', 'Patagonia Refugio pack 28L', 'Made from 630-denier 100% nylon (50% recycled/50% high-tenacity) plain weave; lined with 200-denier 100% recycled polyester. ...', 6.00);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('444434', 'Red Hat Impact T-shirt', 'This 4. 3 ounce, 60% combed ringspun cotton/40% polyester jersey t- shirt features a slightly heathered appearance. The fabric laundered for reduced shrinkage. Next Level brand apparel. Printed.', 9.00);
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('444435', 'Quarkus twill cap', '100% cotton chino twill cap with an unstructured, low-profile, six-panel design. The crown measures 3 1/8 and this features a Permacurv visor and a buckle closure with a grommet.',13.00 );
INSERT INTO PRODUCT (item_id, name, description, price) VALUES ('444437', 'Nanobloc Universal Webcam Cover', 'NanoBloc Webcam Cover fits phone, laptop, desktop, Pc, MacBook Pro, iMac, ...', 2.75);
